chore: container disclaimer, add missing env for smooth setup
learnhouse/docs pull request #38
Opened 2024-10-11 18:14 UTC by chrishollandaise

Related to PR [#334](https://github.com/learnhouse/learnhouse/pull/334)

Changes:
1. Added container memory disclaimer to the docs to help circumvent build failures when compiling the frontend. [#392](https://github.com/learnhouse/learnhouse/issues/329)

2. Added the `NEXT_PUBLIC_LEARNHOUSE_TOP_DOMAIN` to the env sections.

Reason for the second change was I noticed that without this NextJS auth cookies would try to default to being secure, which won't work for `localhost`

2024-10-11 18:28 UTC, chrishollandaise commented
One more thing, when I was setting up. I was confused by the inconsistencies for the env between the step 1 and 2 [frontend configuration section](https://docs.learnhouse.app/setup-dev-environment#frontend-configuration). 

I am wondering if this section should be condensed down to just include all the needed env variables for the setup? I didn't see any unique setup for when `NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG` is set to test, and then set to default in the next step. That goes for the additional env variables that are included.

2024-10-13 14:28 UTC, swve commented
Hey @chrishollandaise, nice finds and LGTM 👍

You're right about the extra step—it doesn't add much value and can definitely be combined with the following one. I originally included it to demonstrate how org detection works based on the 'Hosting Modes', but we can merge the two steps and include a brief note explaining that the multi-org setup won't work locally. 

I'll also link to this page for reference: https://docs.learnhouse.app/self-hosting/organization-hosting-modes

2024-10-13 14:28 UTC, swve reviewed
Hey @chrishollandaise, nice finds and LGTM 👍

You're right about the extra step—it doesn't add much value and can definitely be combined with the following one. I originally included it to demonstrate how org detection works based on the 'Hosting Modes', but we can merge the two steps and include a brief note explaining that the multi-org setup won't work locally.

I'll also link to this page for reference: https://docs.learnhouse.app/self-hosting/organization-hosting-modes

2024-10-13 21:55 UTC, chrishollandaise commented
@swve Glad you agree. That totally makes sense, and I think that once multi-org setup works locally it'll be helpful to future contributors to have some more details.

2024-10-14 21:42 UTC, swve requested changes
One little change and i'll be good to merge

2024-10-14 21:42 UTC, swve commented on pages/setup-dev-environment.mdx
> +NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG=defaultorg
```suggestion
NEXT_PUBLIC_LEARNHOUSE_DEFAULT_ORG=default
```
As that's the exact assigned slug when you first install the backend

2024-10-14 21:58 UTC, swve approved these changes

2024-10-14 21:59 UTC, swve commented
Thanks for your contribution @chrishollandaise 🙏

2024-10-14 21:59 UTC, merged